name: Slack Notifications

on:
  workflow_run:
    workflows: ["Uptime CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack Workspace 1
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Upptime alert"}' \
          ${{ secrets.SLACK_WEBHOOK_1 }}

      - name: Notify Slack Workspace 2
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Upptime alert"}' \
          ${{ secrets.SLACK_WEBHOOK_2 }}
