name: Upptime Notifications

on:
  push:
    paths:
      - "history/*.yml"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check services
        run: |
          for file in history/*.json
          do
            STATUS=$(jq -r '.status' "$file")
            URL=$(jq -r '.url' "$file")

            if [ "$STATUS" = "down" ]; then
              MESSAGE="🚨 DOWN: $URL"
            else
              MESSAGE="✅ RECOVERED: $URL"
            fi

            echo "Sending notification: $MESSAGE"

            # Slack 1
            curl -s -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MESSAGE\"}" \
            ${{ secrets.SLACK_WEBHOOK_1 }}

            # Slack 2
            curl -s -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MESSAGE\"}" \
            ${{ secrets.SLACK_WEBHOOK_2 }}

          done
